version: '3.6'
services:
  celery:
    build:
      context: .
      dockerfile: ./travis/Dockerfile-travis-web
    environment:
      # for celery, to avoid ImproperlyConfigured
      MAILGUN_URL: 'http://fake.example.com'
      MAILGUN_KEY: 'fake'
      ELASTICSEARCH_INDEX: 'testindex'
      OPEN_DISCUSSIONS_SITE_KEY: 'fake'

  web:
    build:
      context: .
      dockerfile: ./travis/Dockerfile-travis-web

  selenium:
    build:
      context: .
      dockerfile: ./travis/Dockerfile-travis-web
